force-app/main/default/objects/Employee_Mileage__c/fields/Bi_Weekly_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Bi_Weekly_Reimbursement__c</fullName>
    <label>Bi Weekly Reimbursement</label>
    <referenceTo>Bi_Weekly_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/mileageremoveapprovaldateTest.cls
@isTest
public class mileageremoveapprovaldateTest {
    @isTest
    public static void TestMethod1(){
        TriggerConfig__c cusmsetting = TestDataFactory.triggerConfigCustomSetting(True);
        SendEmail__c  SendEmailcusmsetting = TestDataFactory.sendEmailCustomSetting(true, 'Send Email For Compliance');
        Vehicle_URL_Mapping__c vehicleType = TestDataFactory.createVehicleData(true, 3);
        IRS_Mileage_Rate__c createIRSRate = TestDataFactory.createIRSRate(true, 0);
        
        Account acc;
        Account acc2;
        List<Contact> con ;
        
        UserRole userRole = TestDataFactory.getUserRole();
        Profile profileObj = TestDataFactory.getUserProfile();
        User admin = TestDataFactory.getSystemAdminUser(userRole.Id);
        User userObj;
        
        System.runAs(admin) {
            acc = TestDataFactory.createAccount(True, 'Test Account', true);
            con = TestDataFactory.createDriverContact(true, acc.Id, 'Driver', vehicleType.Name, 'Paras.Patel', 2); 
            userObj = TestDataFactory.createUser(True, profileObj.Id, con[0].Id);
        }
        List<Employee_Reimbursement__c> er = TestDataFactory.createPendingReimbursement(true, con, 1, createIRSRate.Id);
        List<Bi_Weekly_Reimbursement__c> br = TestDataFactory.createBiweeklyReim (true, con, System.today().addDays(-26),System.today().addDays(-13), 1, createIRSRate.Id);
        List<Employee_Mileage__c> emp1 = TestDataFactory.getEmpMileage (True, 1, er, br);
        
        test.startTest();
        MileageTriggerHandler.MileageRemoveApprovalDateHandler(emp1);
        MileageTriggerHandler.updateWorkingDays(emp1);
        delete emp1;
        test.stopTest();
    }

}